[project]
name = "config"
version = "1.0.0"
description = "Web app for monitoring IP"
dependencies = [
    "blinker==1.8.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "Flask==3.0.3",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.4",
    "MarkupSafe==2.1.5",
    "ping3==4.0.8",
    "Werkzeug==3.0.3",
    "python-dotenv==1.0.1",
    "waitress==3.0.0",
]

[build-system]
requires = ["flit_core<4","setuptools", "wheel"]
build-backend = "flit_core.buildapi"